const employees = [
  //  1
  {
    id: 1,
    imgSrc: "",
    firstName: "Børge",
    lastName: "Hovde",
    address: "Olaf Ryes Plass 1C",
    role: "Daglig leder",
    restaurantId: 1,
  },
  {
    id: 2,
    imgSrc: "",
    firstName: "Markus",
    lastName: "Vigre",
    address: "Sollis Gate 14",
    role: "Kjøkkensjef",
    restaurantId: 1,
  },
  {
    id: 3,
    imgSrc: "",
    firstName: "Jacob",
    lastName: "Engh",
    address: "Kroksvingen 11",
    role: "Kokk",
    restaurantId: 1,
  },
  {
    id: 4,
    imgSrc: "",
    firstName: "Magnus",
    lastName: "Hansen",
    address: "Pizzavegen 44",
    role: "Renholder",
    restaurantId: 1,
  },
  {
    id: 5,
    imgSrc: "",
    firstName: "Frida Karlsen",
    lastName: "Karlsen",
    address: "Majorstuvegen 3",
    role: "Servitør",
    restaurantId: 1,
  },
  //  2
  {
    id: 6,
    imgSrc: "",
    firstName: "Maja",
    lastName: "Fosen",
    address: "Tjuvholmen 121A",
    role: "Daglig leder",
    restaurantId: 2,
  },
  {
    id: 7,
    imgSrc: "",
    firstName: "Ragnhild",
    lastName: "Ringstad",
    address: "Tulipanhagen 12A",
    role: "Kjøkkensjef",
    restaurantId: 2,
  },
  {
    id: 8,
    imgSrc: "",
    firstName: "Tonje",
    lastName: "Bråthen",
    address: "svovelveien 3B",
    role: "Kokk",
    restaurantId: 2,
  },
  {
    id: 9,
    imgSrc: "",
    firstName: "Roy",
    lastName: "Johansen",
    address: "Dronningsgate 7D",
    role: "Servitør",
    restaurantId: 2,
  },
  {
    id: 10,
    imgSrc: "",
    firstName: "Hans",
    lastName: "Reitan",
    address: "Reingata 5C",
    role: "Renholder",
    restaurantId: 2,
  },
  //  3
  {
    id: 11,
    imgSrc: "",
    firstName: "Riad",
    lastName: "Hamli",
    address: "Kakesvingen 15B",
    role: "Daglig leder",
    restaurantId: 3,
  },
  {
    id: 12,
    imgSrc: "",
    firstName: "Kawthar",
    lastName: "Mohamed",
    address: "kirkeplassen 91",
    role: "Kjøkkensjef",
    restaurantId: 3,
  },
  {
    id: 13,
    imgSrc: "",
    firstName: "Stein",
    lastName: "Tran",
    address: "Trangata 7C",
    role: "Kokk",
    restaurantId: 3,
  },
  {
    id: 14,
    imgSrc: "",
    firstName: "Abdi",
    lastName: "Dahli",
    address: "Strandgata 77D",
    role: "Renholder",
    restaurantId: 3,
  },
  {
    id: 15,
    imgSrc: "",
    firstName: "Liri",
    lastName: "Haziri",
    address: "Fiskevegen 11",
    role: "Servitør",
    restaurantId: 3,
  },
  //  4
  {
    id: 16,
    imgSrc: "",
    firstName: "Jonny",
    lastName: "Antonsen",
    address: "Kebabsvingen 15C",
    role: "Daglig leder",
    restaurantId: 3,
  },
  {
    id: 17,
    imgSrc: "",
    firstName: "Einar",
    lastName: "Aarskog",
    address: "Kebabsvingen 15A",
    role: "Kjøkkensjef",
    restaurantId: 3,
  },
  {
    id: 18,
    imgSrc: "",
    firstName: "Arild",
    lastName: "Solli",
    address: "Kebabsvingen 15B",
    role: "Kokk",
    restaurantId: 3,
  },
  {
    id: 19,
    imgSrc: "",
    firstName: "Heidi",
    lastName: "Rusten",
    address: "Kebabsvingen 15B",
    role: "Renholder",
    restaurantId: 3,
  },
  {
    id: 20,
    imgSrc: "",
    firstName: "Benedicte",
    lastName: "Bjørk",
    address: "Storgata 8B",
    role: "Servitør",
    restaurantId: 3,
  },
];
export default employees;
