const menu = [
  {
    id: "1",
    title: "Pepperoni med ananas",
    price: 140,
    imgSrc: "pepperoni.jpg",
    type: "pizza",
    ingredients: "pepperoni",
  },
  {
    id: 2,
    title: "Ost & skinke",
    price: 136,
    imgSrc: "skinke.jpg",
    type: "pizza",
    ingredients: "skinke, ost",
  },
  {
    id: 3,
    title: "Kjøttdeig og løk",
    price: 127,
    imgSrc: "kjøtt_løk.jpg",
    type: "pizza",
    ingredients: "kjøtt, løk",
  },
  {
    id: 4,
    title: "Veggis",
    price: 110,
    imgSrc: "veggis.jpg",
    type: "pizza",
    ingredients: "",
  },
  {
    id: 5,
    title: "Crazy meatlover",
    price: 157,
    imgSrc: "kjøttelsker.jpg",
    type: "pizza",
    ingredients: "pepperoni, skinke, kjøtt",
  },
  {
    id: 6,
    title: "Brus",
    price: 40,
    imgSrc: "cola.png",
    type: "drink",
  },
  {
    id: 7,
    title: "Øl",
    price: 69,
    imgSrc: "øl.png",
    type: "drink",
  },
  {
    id: 8,
    title: "Cider",
    price: 71,
    imgSrc: "cider.png",
    type: "drink",
  },
  {
    id: 9,
    title: "Vin",
    price: 120,
    imgSrc: "placeholder.png",
    type: "drink",
  },
];
//export default menu;
