const menu = [
  {
    id: 1,
    title: "Pepperoni med ananas",
    price: 140,
    imgSrc: "",
    type: "pizza",
    ingredients: "",
  },
  {
    id: 2,
    title: "Ost & skinke",
    price: 136,
    imgSrc: "",
    type: "pizza",
    ingredients: "",
  },
  {
    id: 3,
    title: "Kjøttdeig og løk",
    price: 127,
    imgSrc: "",
    type: "pizza",
    ingredients: "",
  },
  {
    id: 4,
    title: "Veggis",
    price: 110,
    imgSrc: "",
    type: "pizza",
    ingredients: "",
  },
  {
    id: 5,
    title: "Crazy meatlover",
    price: 157,
    imgSrc: "",
    type: "pizza",
    ingredients: "",
  },
  {
    id: 6,
    title: "Brus",
    price: 40,
    imgSrc: "",
    type: "drink",
  },
  {
    id: 7,
    title: "Øl",
    price: 69,
    imgSrc: "",
    type: "drink",
  },
  {
    id: 8,
    title: "Cider",
    price: 71,
    imgSrc: "",
    type: "drink",
  },
  {
    id: 9,
    title: "Vin",
    price: 120,
    imgSrc: "",
    type: "drink",
  },
];
export default menu;
